# Generated by Django 5.2.1 on 2025-06-02 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('web_image_url', models.TextField(blank=True, null=True)),
                ('defect_type', models.TextField(blank=True, null=True)),
                ('current_saturation', models.FloatField(blank=True, null=True)),
                ('reference_saturation', models.FloatField(blank=True, null=True)),
                ('tolerance', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'defects_table',
                'ordering': ['-timestamp'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirm_defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirm', to='quality_app.defect')),
            ],
            options={
                'db_table': 'confirmed_defects',
                'ordering': ['-confirm_timestamp'],
                'managed': True,
            },
        ),
    ]
