services:
  kafka:
    image: bitnami/kafka:3.7.0
    ports:
      - "9094:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      # KRaft settings
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_KRAFT_CLTER_ID=HsDBs9l6UUmQq7Y5E6bNlw
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@Kafka00Service:9093,1@Kafka01Service:9093,2@Kafka02Service:9093
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # Listeners
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:10000
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://Kafka00Service:9092,EXTERNAL://localhost:10000
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Clustering
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=3
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=2
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 # 컨테이너 시작 시 실행할 명령어
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/data
      - django_media:/app/media
    environment:
      - DATABASE_PATH=/app/data/quality_defects.db_data
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MEDIA_ROOT=/app/media
    depends_on:
      - kafka
  consumer:
    build: .
    command: python main_consumer.py
    volumes:
      - db_data:/app/data
    environment:
      - DATABASE_PATH=/app/data/quality_defects.db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
  producer:
    build: .
    command: python main_producer.py
    volumes:
      - data_to_process:/app/data/to_process 
      - db_data:/app/data 
      - django_media:/app/media
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    
volumes:
  kafka_data:
  db_data:
  django_media:
  data_to_process:

    